### ISSUE TITLE
can you give me documentation of it's coding 

### ISSUE THREAD

**Issue by waqaramjad** [KarthikNedunchezhiyan/Image-Mimic-Genetic-Algorithm#2]
can you give me documentation of it's coding  because there is a confusion in many things 
1)  how this randomly image formed ?
2) i checked the code you did not use import any where like to link the file so how this file connected to main.js ?
3) why there is an error when we refresh the page of "max call exceed " ?

it's really good you could explain that things 
thanks in advance

**Comment by KarthikNedunchezhiyan** [comment]
Hi @waqaramjad sorry for the delayed response.

> 1. how this randomly image formed ?

Here I am using a sandpile algorithm to construct random images. Implementation is in [imageGenerator.js](https://github.com/KarthikNedunchezhiyan/Image-Mimic-Genetic-Algorithm/blob/b7407aee78e04f2bf96f4ea01c07e7283a2975e4/src/js/imageGenerator.js#L1)

> 2. i checked the code you did not use import any where like to link the file so how this file connected to main.js ?

It is linked on [index.html](https://github.com/KarthikNedunchezhiyan/Image-Mimic-Genetic-Algorithm/blob/b7407aee78e04f2bf96f4ea01c07e7283a2975e4/src/html/index.html#L79)

> 3. why there is an error when we refresh the page of "max call exceed " ?

This happens due to high recursion calls while creating random image. This will mostly happen in mobile browsers as their call stack limit will be less than desktop. To avoid this you could adjust [image size](https://github.com/KarthikNedunchezhiyan/Image-Mimic-Genetic-Algorithm/blob/b7407aee78e04f2bf96f4ea01c07e7283a2975e4/src/js/main.js#L5) as recursion call is proportional to image size or you could rewrite the recursion logic in [imageGenerator.js](https://github.com/KarthikNedunchezhiyan/Image-Mimic-Genetic-Algorithm/blob/b7407aee78e04f2bf96f4ea01c07e7283a2975e4/src/js/imageGenerator.js#L1)

Happy Coding!
